### ISSUE TITLE
Add belgianairways.com

### ISSUE THREAD

**Issue by kenlju** [disposable-email-domains/disposable-email-domains#509] opened 2024-08-23 09:55 UTC
Has been used in scripting for creating fake accounts

**Comment by kenlju** [comment] 2024-08-28 09:43
Domain exists in other lists.

https://github.com/beeyev/disposable-email-filter-php/releases/tag/v1.3.15

https://www.usercheck.com/domain/belgianairways.com?ref=mailcheck

https://verifymail.io/domain/belgianairways.com

**Comment by martenson** [comment] 2024-09-10 08:39
@kenlju This repo gathers domains that offer services of disposable email provider. Please point at a place where I can create a disposable email with `@belgianairways.com` or close this issue.

**Comment by martenson** [comment] 2024-09-10 08:41
dupe of #501

**Closed by martenson** 2024-09-10 08:41 UTC
Labels: irreproducible
